#!/bin/bash

# 🚀 Quick Test Guide for Admin Dashboard Fix

echo "================================"
echo "🔧 Admin Dashboard Fix - Test"
echo "================================"

echo ""
echo "Step 1: Verify Database Setup"
echo "-----"
node test-admin-auth.js

echo ""
echo "Step 2: Start Dev Server with Clean Build"
echo "-----"
echo "Run: npm run dev:clean"
echo ""
echo "Then wait for:"
echo "  ▲ Next.js v15.x.x"
echo "  - Local: http://localhost:3000"
echo ""

echo "Step 3: Test Admin Login"
echo "-----"
echo "1. Open: http://localhost:3000"
echo "2. Login with:"
echo "   Email: admin@absensi.test"
echo "   Password: password"
echo ""

echo "Step 4: Verify Session"
echo "-----"
echo "After login, check:"
echo "  http://localhost:3000/api/debug/session"
echo ""
echo "Expected output:"
echo "  {"
echo "    \"authenticated\": true,"
echo "    \"user\": {"
echo "      \"can_admin\": true,"
echo "      \"nama\": \"Admin HRD\","
echo "      ..."
echo "    }"
echo "  }"
echo ""

echo "Step 5: Test Admin Dashboard Access"
echo "-----"
echo "1. Navigate to: http://localhost:3000/admin/dashboard"
echo "2. Expected: Dashboard loads (NOT redirect to /pegawai/dashboard) ✅"
echo ""

echo "Step 6: Test Non-Admin Redirect"
echo "-----"
echo "1. Login as pegawai:"
echo "   Email: andi@absensi.test"
echo "   Password: password"
echo "2. Try access: http://localhost:3000/admin/dashboard"
echo "3. Expected: Redirect to /pegawai/dashboard ✅"
echo ""

echo "================================"
echo "✨ If all tests pass, you're done!"
echo "================================"
